### ISSUE TITLE
Pip install / wheel for windows?

### ISSUE THREAD

**Issue by cristianocca** [mduggan/cdifflib#1]
Running pip install cdifflib from windows fails to compile, is it possible to have a pre-compiled wheel (or w/e is currently used by other packages to avoid compiling on Windows) ?

Here's the error:

running install
running build
running build_py
creating build
creating build\lib.win32-2.7
copying cdifflib.py -> build\lib.win32-2.7
running build_ext
building '_cdifflib' extension
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -Ic:\python27\include -Ic:\python27\PC /Tc_cdifflib.c /Fobuild\temp.win32-2.7\Release\_cdifflib.obj
_cdifflib.c
_cdifflib.c(7) : error C2054: expected '(' to follow 'inline'
_cdifflib.c(8) : error C2085: 'list_items_eq' : not in formal parameter list
_cdifflib.c(8) : error C2143: syntax error : missing ';' before '{'
_cdifflib.c(20) : error C2054: expected '(' to follow 'inline'
_cdifflib.c(21) : error C2085: 'call_obj' : not in formal parameter list
_cdifflib.c(21) : error C2143: syntax error : missing ';' before '{'
_cdifflib.c(140) : warning C4013: 'call_obj' undefined; assuming extern returning int
_cdifflib.c(141) : warning C4013: 'list_items_eq' undefined; assuming extern returning int
_cdifflib.c(401) : error C2143: syntax error : missing ';' before 'type'
_cdifflib.c(404) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(404) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(404) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(406) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(406) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(406) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(413) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(413) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(413) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(458) : error C2061: syntax error : identifier 'CDiffLibMethods'
_cdifflib.c(458) : error C2059: syntax error : ';'
_cdifflib.c(458) : error C3409: empty attribute block is not allowed
_cdifflib.c(458) : error C2513: '/*global*/ ' : no variable declared before '='
_cdifflib.c(476) : error C2065: 'CDiffLibMethods' : undeclared identifier
_cdifflib.c(476) : warning C4047: 'function' : 'PyMethodDef *' differs in levels of indirection from 'int'
_cdifflib.c(476) : warning C4024: 'Py_InitModule4' : different types for formal and actual parameter 2
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe' failed with exit status 2

**Comment by mduggan** [comment]
Thanks for the report! I'd never tried compiling on windows so it's not a huge surprise that it's not totally compatible.

I made some tweaks to the code that should make the MS compiler happy, although I'm not totally sure about line 458 on.

Could you try again and let me know how it goes?

**Comment by cristianocca** [comment]
Same issue, it might be me, or the windows C compiled is expecting a different C syntax from maybe an older version, I'm no C expert, but this might be related: https://stackoverflow.com/questions/24736304/unable-to-use-inline-in-declaration-get-error-c2054

python setup.py install
running install
running bdist_egg
running egg_info
creating cdifflib.egg-info
writing cdifflib.egg-info\PKG-INFO
writing top-level names to cdifflib.egg-info\top_level.txt
writing dependency_links to cdifflib.egg-info\dependency_links.txt
writing manifest file 'cdifflib.egg-info\SOURCES.txt'
reading manifest file 'cdifflib.egg-info\SOURCES.txt'
writing manifest file 'cdifflib.egg-info\SOURCES.txt'
installing library code to build\bdist.win32\egg
running install_lib
running build_py
creating build
creating build\lib.win32-2.7
copying cdifflib.py -> build\lib.win32-2.7
running build_ext
building '_cdifflib' extension
creating build\temp.win32-2.7
creating build\temp.win32-2.7\Release
C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python27\include -IC:\Python27\PC /Tc_cdifflib.c /Fobuild\temp.win32-2.7\Release\_cdifflib.obj
_cdifflib.c
_cdifflib.c(7) : error C2054: expected '(' to follow 'inline'
_cdifflib.c(8) : error C2085: 'list_items_eq' : not in formal parameter list
_cdifflib.c(8) : error C2143: syntax error : missing ';' before '{'
_cdifflib.c(20) : error C2054: expected '(' to follow 'inline'
_cdifflib.c(21) : error C2085: 'call_obj' : not in formal parameter list
_cdifflib.c(21) : error C2143: syntax error : missing ';' before '{'
_cdifflib.c(140) : warning C4013: 'call_obj' undefined; assuming extern returning int
_cdifflib.c(141) : warning C4013: 'list_items_eq' undefined; assuming extern returning int
_cdifflib.c(401) : error C2143: syntax error : missing ';' before 'type'
_cdifflib.c(404) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(404) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(404) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(406) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(406) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(406) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(413) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(413) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(413) : error C2065: 'fastkeys' : undeclared identifier
_cdifflib.c(458) : error C2061: syntax error : identifier 'CDiffLibMethods'
_cdifflib.c(458) : error C2059: syntax error : ';'
_cdifflib.c(458) : error C3409: empty attribute block is not allowed
_cdifflib.c(458) : error C2143: syntax error : missing ']' before 'constant'
_cdifflib.c(476) : error C2065: 'CDiffLibMethods' : undeclared identifier
_cdifflib.c(476) : warning C4047: 'function' : 'PyMethodDef *' differs in levels of indirection from 'int'
_cdifflib.c(476) : warning C4024: 'Py_InitModule4' : different types for formal and actual parameter 2
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe' failed with exit status 2

**Comment by mduggan** [comment]
Hmm.. is that just doing pip install or using the code from github?  Sorry, I hadn't actually pushed a new version to pypi so pip install is still going to fail.  The changes won't affect linux/macos though so I'll just push a new version there now.

**Comment by cristianocca** [comment]
I downloaded the repo and tried to install it.


-------- Mensaje original --------
De: Matthew Duggan <notifications@github.com>
Fecha: 9/7/17 3:07 (GMT-03:00)
Para: mduggan/cdifflib <cdifflib@noreply.github.com>
Cc: Cristiano Coelho <cristianocca@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [mduggan/cdifflib] Pip install / wheel for windows? (#1)


Hmm.. is that just doing pip install or using the code from github? Sorry, I hadn't actually pushed a new version to pypi so pip install is still going to fail. The changes won't affect linux/macos though so I'll just push a new version there now.

**Comment by mduggan** [comment]
Ok, I got a windows VM and worked it out, should work now.  Also uploaded a windows version while I was at it 🎉

**Comment by cristianocca** [comment]
Great, it worked! Thanks.

**Comment by mduggan** [comment]
Cool, thanks for the report. Fixed in 1.0.4.
