### ISSUE TITLE
CSequenceMatcher.set_seq1 does not reset necessary internal states

### ISSUE THREAD

**Issue by Lnkvct** [mduggan/cdifflib#10]
The `ratio` should be recalculated after seq1 is set. 
```
>>> from cdifflib import CSequenceMatcher
>>> s = CSequenceMatcher(None, "abcd", "bcde")
>>> s.ratio()
0.75
>>> s.set_seq1("bcde")
>>> s.ratio()
0.75                                       # expected to be 1
>>> s = CSequenceMatcher(None, "bcde", "bcde")
>>> s.ratio()
1.0
```
Adding `self.matching_blocks = self.opcodes = None` to the end of the method `set_seq1` can solve this problem.

**Comment by mduggan** [comment]
Thanks for the catch! I just pushed the fix, will bump the version in pypi in the next couple of days.

**Comment by mduggan** [comment]
Uploaded 1.2.6 to pypi.
